//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLConnectionLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Contacts = new HashSet<Contacts>();
            this.Contacts1 = new HashSet<Contacts>();
            this.Rentals = new HashSet<Rentals>();
            this.Rentals1 = new HashSet<Rentals>();
            this.ServiceWorksheets = new HashSet<ServiceWorksheets>();
        }
    
        public long customerID { get; set; }
        public string customerName { get; set; }
        public string IDNumber { get; set; }
        public string mothersName { get; set; }
        public Nullable<long> cityID { get; set; }
        public string customerAddress { get; set; }
        public string customerPhone { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string workPlace { get; set; }
        public bool isFirm { get; set; }
        public string comment { get; set; }
        public string problems { get; set; }
        public Nullable<double> defaultDiscount { get; set; }
        public int rentCounter { get; set; }
        public int serviceCounter { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual Cities Cities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacts> Contacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacts> Contacts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rentals> Rentals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rentals> Rentals1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceWorksheets> ServiceWorksheets { get; set; }
    }
}
