//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLConnectionLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailedCustomers
    {
        public long customerID { get; set; }
        public string customerName { get; set; }
        public string IDNumber { get; set; }
        public string mothersName { get; set; }
        public Nullable<long> cityID { get; set; }
        public string customerAddress { get; set; }
        public string customerPhone { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string workPlace { get; set; }
        public bool isFirm { get; set; }
        public string comment { get; set; }
        public string problems { get; set; }
        public Nullable<double> defaultDiscount { get; set; }
        public int rentCounter { get; set; }
        public int serviceCounter { get; set; }
        public bool customerDeleted { get; set; }
        public string postalCode { get; set; }
        public string city { get; set; }
        public Nullable<bool> cityDeleted { get; set; }
    }
}
