//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLConnectionLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parts
    {
        public long partID { get; set; }
        public long serviceID { get; set; }
        public string partName { get; set; }
        public string partManufacturer { get; set; }
        public string partIDNumber { get; set; }
        public long partPrice { get; set; }
        public int partQuantity { get; set; }
        public bool mustOrder { get; set; }
    
        public virtual ServiceWorksheets ServiceWorksheets { get; set; }
    }
}
