//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLConnectionLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rentals
    {
        public long rentalID { get; set; }
        public long customerID { get; set; }
        public Nullable<long> contactID { get; set; }
        public long toolID { get; set; }
        public System.DateTime rentalStart { get; set; }
        public System.DateTime rentalEnd { get; set; }
        public Nullable<System.DateTime> rentalRealEnd { get; set; }
        public long actualPrice { get; set; }
        public long payTypeID { get; set; }
        public float discount { get; set; }
        public bool isClean { get; set; }
        public long groupID { get; set; }
        public bool isPaid { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Customers Customers1 { get; set; }
        public virtual PayTypes PayTypes { get; set; }
        public virtual RentalGroups RentalGroups { get; set; }
        public virtual Tools Tools { get; set; }
    }
}
