//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLConnectionLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalSum
    {
        public long customerID { get; set; }
        public string customerName { get; set; }
        public string cIDNumber { get; set; }
        public string mothersName { get; set; }
        public string customerAddress { get; set; }
        public string customerPhone { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string workPlace { get; set; }
        public bool isFirm { get; set; }
        public string comment { get; set; }
        public string problems { get; set; }
        public long toolID { get; set; }
        public string toolName { get; set; }
        public string toolManufacturer { get; set; }
        public string tIDNumber { get; set; }
        public string serialNumber { get; set; }
        public string contactName { get; set; }
        public System.DateTime rentalStart { get; set; }
        public System.DateTime rentalEnd { get; set; }
        public long actualPrice { get; set; }
        public float discount { get; set; }
        public long groupID { get; set; }
        public long rentalID { get; set; }
        public bool isPaid { get; set; }
        public Nullable<System.DateTime> rentalRealEnd { get; set; }
        public bool isClean { get; set; }
        public long payTypeID { get; set; }
        public Nullable<double> defaultDiscount { get; set; }
        public int cRentCounter { get; set; }
        public int serviceCounter { get; set; }
        public long rentPrice { get; set; }
        public long toolStatusID { get; set; }
        public System.DateTime fromDate { get; set; }
        public Nullable<long> defaultDeposit { get; set; }
        public int tRentCounter { get; set; }
        public string contactIDNumber { get; set; }
        public string contactMothersName { get; set; }
        public string contactAddress { get; set; }
        public string contactPhone { get; set; }
        public Nullable<System.DateTime> contactBirthDate { get; set; }
        public string contactWorkplace { get; set; }
        public string contactComment { get; set; }
        public string contactProblems { get; set; }
        public bool tIsDeleted { get; set; }
        public bool cIsDeleted { get; set; }
        public Nullable<long> customerCityID { get; set; }
        public string customerPostalCode { get; set; }
        public string customerCity { get; set; }
        public Nullable<long> contactCityID { get; set; }
        public string contactPostalCode { get; set; }
        public string contactCity { get; set; }
    }
}
