//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLConnectionLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceSum
    {
        public long customerID { get; set; }
        public string customerName { get; set; }
        public string IDNumber { get; set; }
        public string mothersName { get; set; }
        public string customerAddress { get; set; }
        public string customerPhone { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string workPlace { get; set; }
        public bool isFirm { get; set; }
        public string custComment { get; set; }
        public string problems { get; set; }
        public Nullable<double> defaultDiscount { get; set; }
        public long worksheetID { get; set; }
        public string deviceID { get; set; }
        public string deviceManufacturer { get; set; }
        public string deviceName { get; set; }
        public bool hasWarranty { get; set; }
        public long errorTypeID { get; set; }
        public string errorDescription { get; set; }
        public long statusID { get; set; }
        public System.DateTime serviceStart { get; set; }
        public Nullable<System.DateTime> serviceEnd { get; set; }
        public bool isPaid { get; set; }
        public Nullable<long> serviceCost { get; set; }
        public string wsComment { get; set; }
        public double discount { get; set; }
        public string statusName { get; set; }
        public string errorType { get; set; }
        public bool inQuotMode { get; set; }
        public bool quotRequested { get; set; }
        public string plusParts { get; set; }
        public int yearCounter { get; set; }
        public bool quotAccepted { get; set; }
        public string serialID { get; set; }
        public Nullable<System.DateTime> buyDate { get; set; }
        public string warrantyNumber { get; set; }
        public Nullable<long> maxCost { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<long> cityID { get; set; }
        public string postalCode { get; set; }
        public string city { get; set; }
    }
}
