//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLConnectionLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceWorksheets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceWorksheets()
        {
            this.Parts = new HashSet<Parts>();
        }
    
        public long worksheetID { get; set; }
        public long customerID { get; set; }
        public string serialID { get; set; }
        public string deviceID { get; set; }
        public string deviceManufacturer { get; set; }
        public string deviceName { get; set; }
        public bool hasWarranty { get; set; }
        public long errorTypeID { get; set; }
        public string errorDescription { get; set; }
        public long statusID { get; set; }
        public System.DateTime serviceStart { get; set; }
        public Nullable<System.DateTime> serviceEnd { get; set; }
        public bool isPaid { get; set; }
        public Nullable<long> groupID { get; set; }
        public Nullable<long> serviceCost { get; set; }
        public string comment { get; set; }
        public double discount { get; set; }
        public bool inQuotMode { get; set; }
        public bool quotRequested { get; set; }
        public bool quotAccepted { get; set; }
        public string plusParts { get; set; }
        public int yearCounter { get; set; }
        public Nullable<System.DateTime> buyDate { get; set; }
        public string warrantyNumber { get; set; }
        public Nullable<long> maxCost { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual ErrorTypes ErrorTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parts> Parts { get; set; }
        public virtual ServiceStatuses ServiceStatuses { get; set; }
    }
}
