//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLConnectionLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemParameters
    {
        public long parameterID { get; set; }
        public string companyName { get; set; }
        public string companyAddress { get; set; }
        public string companyPhone1 { get; set; }
        public string companyPhone2 { get; set; }
        public string openTime { get; set; }
        public Nullable<long> costOfClean { get; set; }
    }
}
