//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLConnectionLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tools
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tools()
        {
            this.Rentals = new HashSet<Rentals>();
        }
    
        public long toolID { get; set; }
        public string toolName { get; set; }
        public string toolManufacturer { get; set; }
        public string IDNumber { get; set; }
        public string serialNumber { get; set; }
        public long rentPrice { get; set; }
        public long toolStatusID { get; set; }
        public System.DateTime fromDate { get; set; }
        public Nullable<long> defaultDeposit { get; set; }
        public int rentCounter { get; set; }
        public bool isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rentals> Rentals { get; set; }
        public virtual ToolStatuses ToolStatuses { get; set; }
    }
}
